import { NextRequest, NextResponse } from "next/server";
import archiver from "archiver";
import { PassThrough } from "stream";
import { loadMemory } from "@/lib/memory/store";
import {
  generatePitchDeckMarkdown,
  generateFinancialModelCsv,
  generateLeadsCsv,
  generateTasksCsv,
  generateLandingPageHtml,
  generateScorecardMarkdown,
} from "@/lib/tools/toolbox";
import { generatePDFHtml } from "@/lib/tools/pdf";
import { saveToolRun } from "@/lib/database/tool-runs";

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const memoryId = searchParams.get("id");
  if (!memoryId) return NextResponse.json({ error: "id required" }, { status: 400 });

  const memory = loadMemory(memoryId);
  if (!memory) return NextResponse.json({ error: "Session not found" }, { status: 404 });

  if (Object.keys(memory.agentOutputs).length === 0) {
    return NextResponse.json({ error: "No agent outputs yet" }, { status: 400 });
  }

  const slug = memory.startupName.replace(/[^a-z0-9]/gi, "-").toLowerCase();

  const archive = archiver("zip", { zlib: { level: 9 } });
  const passthrough = new PassThrough();
  archive.pipe(passthrough);

  archive.append(generatePitchDeckMarkdown(memory), { name: "pitch-deck.md" });
  archive.append(generateFinancialModelCsv(memory), { name: "financial-model.csv" });
  archive.append(generateLeadsCsv(memory), { name: "crm-leads.csv" });
  archive.append(generateTasksCsv(memory), { name: "engineering-tasks.csv" });
  archive.append(generateLandingPageHtml(memory), { name: "landing-page.html" });
  archive.append(generatePDFHtml(memory), { name: "full-report.html" });
  archive.append(generateScorecardMarkdown(memory), { name: "founder-scorecard.md" });

  // Raw agent outputs, one file each, for anyone who wants the unformatted source text.
  for (const [agent, output] of Object.entries(memory.agentOutputs)) {
    archive.append(output, { name: `agent-outputs/${agent}.md` });
  }

  const readme = `# ${memory.startupName} — Launch Kit

Generated by Founder Orchestrator on ${new Date().toLocaleDateString()}.

## Contents
- pitch-deck.md — 12-section investor pitch deck draft
- financial-model.csv — 12-month revenue, CAC, and burn model
- crm-leads.csv — ICP segments, lead sources, and outreach angles
- engineering-tasks.csv — Sprint-ready task list with owners and priority
- landing-page.html — Standalone waitlist landing page (open directly in a browser)
- full-report.html — Combined report of all agent outputs (print to PDF from your browser)
- founder-scorecard.md — Judge Mode score breakdown and critique (if Judge Mode was run)
- agent-outputs/ — Raw markdown output from each of the 6 (or 7) agents

## The idea
${memory.idea}
`;
  archive.append(readme, { name: "README.md" });

  archive.finalize();

  saveToolRun({
    memoryId,
    startupName: memory.startupName,
    action: "launch-kit",
    title: "One-Click Launch Kit",
    summary: "Generated a full launch kit zip: pitch deck, financial model, leads, tasks, landing page, and scorecard.",
  });

  const chunks: Buffer[] = [];
  for await (const chunk of passthrough) {
    chunks.push(chunk as Buffer);
  }
  const zipBuffer = Buffer.concat(chunks);

  return new NextResponse(zipBuffer, {
    headers: {
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="${slug}-launch-kit.zip"`,
    },
  });
}
